pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/EDDYCKEDAR/alx-backend-python.git'
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-credentials-id',
                    url: "${GITHUB_REPO}",
                    git branch: 'main'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh 'pytest messaging_app/tests/ --junitxml=test-results.xml'
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'test-results.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("eddyckedar/messaging_app:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
